CREATE DATABASE InvoiceDWH

Go

use InvoiceDWH

CREATE TABLE [dbo].[raw_data] (
        INVOICE VARCHAR(20),
        CUSTOMER VARCHAR(20),
        PRODUCT VARCHAR(20),
        DESCRIPTION NVARCHAR(255),
        DATE DATETIME,
        COUNTRY nvarchar(100),
        QUANTITY INT,
        PRICE DECIMAL(10,2)
    );
GO


CREATE TABLE [dbo].[DIM_CUSTOMER](
	[CUSTOMER_ID] [int] IDENTITY(1,1) NOT NULL,
	[CUSTOMER] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CUSTOMER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[DIM_COUNTRY](
	[COUNTRY_ID] [int] IDENTITY(1,1) NOT NULL,
	[COUNTRY_NAME] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[COUNTRY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DIM_DATE](
	[DATE_ID] [bigint] NOT NULL,
	[INVOICE_DATE] [date] NOT NULL,
	[YEAR] [int] NOT NULL,
	[MONTH] [int] NOT NULL,
	[DAY] [int] NOT NULL,
	[WEEKDAY] [int] NOT NULL,
	[QUARTER] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[DATE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DIM_PRODUCT](
	[PRODUCT_ID] [int] IDENTITY(1,1) NOT NULL,
	[STOCKCODE] [varchar](50) NOT NULL,
	[DESCRIPTION] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[PRODUCT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[FACT_SALES](
	[SALES_ID] [int] IDENTITY(1,1) NOT NULL,
	[INVOICE_ID] [varchar](20) NULL,
	[CUSTOMER_ID] [varchar](20) NULL,
	[PRODUCT_ID] [varchar](50) NULL,
	[DATE_ID] [int] NOT NULL,
	[COUNTRY_ID] [int] NOT NULL,
	[QUANTITY] [int] NOT NULL,
	[PRICE] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SALES_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE INDEX IDX_SALES_DATE ON dbo.FACT_SALES(DATE_ID);
CREATE INDEX IDX_SALES_COUNTRY ON dbo.FACT_SALES(COUNTRY_ID);
CREATE INDEX IDX_SALES_PRODUCT ON dbo.FACT_SALES(PRODUCT_ID);